baseURL = 'https://xjtn18.github.io'
languageCode = 'en-us'
title = "Jacob Nardone's Portfolio & Blog"
theme = 'PaperMod'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
